# amazon search query
search_query: "shirt"
search_category: "fashion-womens-clothing"
# the minimum reviews amount for a product to be fetched
min_reviews: 1
# how many products to fetch
max_products: 10000

# delay intervals between requests - seconds
min_delay: 2
max_delay: 5

# folders settings to where to put the outputs to
data_folder: "data"
tables_folder: "tables"
search_results_folder: "search_results"
# folders inside search_results
faces_folder: "faces"
half_face_folder: "half_face"
jsons_folder: "data_jsons"

processed_pairs_folder: "processed"

# scraping options
# amazon can block our requests. changing the header may help. try changing back and forth to 0 or 1 if not working
header_option: 1
headers: ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36",
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36"]