# amazon search query
search_query: "shirt"
search_category: "fashion-womens-clothing"
# the minimum reviews amount for a product to be fetched
min_reviews: 1
# how many products to fetch
max_products: 10000

# delay intervals between requests - seconds
min_delay: 4
max_delay: 10

# folders settings to where to put the outputs to
data_folder: "data"
tables_folder: "tables"
search_results_folder: "search_results"
# folders inside search_results
faces_folder: "faces"
half_face_folder: "half_face"
jsons_folder: "data_jsons"

processed_pairs_folder: "processed"

# Overwrite data when downloading reviews? set to True or False
overwrite_data: True

# scraping options
# amazon can block our requests. changing the header may help. try changing back and forth to 0 or 1 if not working
header_option: 0
headers: ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36",
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36"]

# processed glued files resized width in pixels (height will adjust automatically).
# to avoid large files (anyhow all we need later is the filenames)
# 0 means no resizing
resize_width: 800
# file format to save the processed images. "jpg" or "png".
# jpg will result with lower file sizes (and faster processing)
processed_fileformat: "jpg"
